### ISSUE TITLE
TypeError: user_followers() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by daniel-ed** [simonseo/instacrawler-privateapi#7]
This is a new error appearing since a few days. 

Has anyone an idea what is happening? I am using the latest crawler and private-API version.

**Comment by simonseo** [comment]
Hi @daniel-ed. 

Thank you for submitting the issue. This is probably due to the recent change in the API.

`user_followers` now takes `user_id` and `rank_token` as it can be seen [here]( https://github.com/ping/instagram_private_api/blob/ca003778bc8c8b7abef6c6f61d6e791ca83a0cb7/instagram_private_api/endpoints/friendships.py#L46)

I'll update it now to reflect the changes.

**Comment by daniel-ed** [comment]
And is there an example for how to use it? Unfortunately I do not understand how rank_token has to be used! :-(

**Comment by daniel-ed** [comment]
Even the example itself (pagination.py) doesn't work anymore!

**Comment by simonseo** [comment]
This was the same issue in a [similar repository that I have](https://github.com/simonseo/instagram-hashtag-crawler/commit/2011b7a434c05ffa2cdd85ef4812037d56fd189b). 

I'll fix it within the next hour.

**Comment by daniel-ed** [comment]
Perfect! Thanks so much!

**Comment by simonseo** [comment]
@daniel-ed, I updated the problematic parts. please check that everything works properly.

**Comment by daniel-ed** [comment]
works perfectly 👍 
Thanks for the quick help!
